Fix crash on karma config without browserify property
Fixes this error:

    node_modules/karma-browserify/lib/index.js:148
        extensions: config.extension,
                      ^
    TypeError: Cannot read property 'extension' of undefined
        at configuredBrowserify

If your karma config module doesn't have a "browserify" property at all.

Uses mostly coffeescript function argument default value syntax